In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('IRIS.csv')
data.head(10)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [14]:
#Выделение тренировочной и тестовой выборки
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
X = data[['sepal_length','sepal_width','petal_length','petal_width']]
y = data['species']
X_train, y_train, X_valid, y_valid = train_test_split(X,y,test_size=0.5,random_state=17)

In [17]:
#LabelEncoder
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
columnsToEncode = list(data.select_dtypes(include=['category','object']))#Столбцы для кодирования

for feature in columnsToEncode:
    data[feature] = lb.fit_transform(data[feature])#fit-transform

X_enc = data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
Y_enc = data['species']

x_train, x_test, y_train, y_test = train_test_split(X_enc, Y_enc, test_size=0.20)#train-test-split

data

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
classifier = DecisionTreeClassifier()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
print(accuracy_score(y_test,y_pred))

1.0


In [21]:
print(y_pred)

[0 2 0 1 1 2 2 0 0 1 1 2 0 0 2 1 0 0 2 0 1 2 1 0 0 0 2 0 2 2]


In [23]:
#confusion matrix, precision, recall and F1 score
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[13  0  0]
 [ 0  7  0]
 [ 0  0 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

